# Generated by Django 4.2.7 on 2026-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taxprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxprofile',
            name='taxpayer_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('business', 'Business'), ('ngo', 'NGO / Non-Profit')], max_length=20),
        ),
    ]
