# Generated by Django 6.0.4 on 2026-04-24 14:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_type', models.CharField(choices=[('personal_income', 'Personal Income Tax'), ('business_income', 'Business Income Tax'), ('vat', 'Value Added Tax (VAT)'), ('turnover', 'Turnover Tax (TOT)'), ('withholding', 'Withholding Tax')], max_length=30)),
                ('filing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('fiscal_year', models.IntegerField()),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('period_quarter', models.IntegerField(blank=True, null=True)),
                ('gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowable_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculated_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_filings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_filings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCalculationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_details', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_log', to='tax_filing.taxfiling')),
            ],
            options={
                'db_table': 'tax_calculation_logs',
            },
        ),
        migrations.CreateModel(
            name='TaxFilingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='tax_documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tax_filing.taxfiling')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_filing_documents',
            },
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['user', 'tax_type', 'fiscal_year'], name='tax_filings_user_id_90a3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['status'], name='tax_filings_status_19069c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['due_date'], name='tax_filings_due_dat_aea462_idx'),
        ),
    ]
