# Generated by Django 6.0.4 on 2026-04-24 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_filing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('fiscal_year', models.IntegerField()),
            ],
            options={
                'db_table': 'compliance_certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='FilingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filing_status_history',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('deadline', 'Deadline Reminder'), ('urgent', 'Urgent')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_from', models.DateTimeField()),
                ('show_until', models.DateTimeField(blank=True, null=True)),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('taxpayer', 'Taxpayers Only'), ('tax_officer', 'Officers Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='amendment_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='appeal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='appeal_outcome',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='appeal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='appeal_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='days_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='is_amendment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='is_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='original_filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='tax_filing.taxfiling'),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='penalty_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taxfiling',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('amended', 'Amended'), ('appealed', 'Under Appeal'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxfilingdocument',
            name='document_type',
            field=models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('bank_statement', 'Bank Statement'), ('appeal_letter', 'Appeal Letter'), ('amendment_support', 'Amendment Supporting Doc'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='taxfiling',
            index=models.Index(fields=['reference_number'], name='tax_filings_referen_7cc8f2_idx'),
        ),
        migrations.AddField(
            model_name='compliancecertificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancecertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filingstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filingstatushistory',
            name='filing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tax_filing.taxfiling'),
        ),
        migrations.AddField(
            model_name='systemannouncement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
