# Generated by Django 4.2.7 on 2026-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_filing', '0004_taxassessmentnotice_officialpaymentreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfiling',
            name='ethiopian_fiscal_year',
            field=models.IntegerField(blank=True, help_text='Ethiopian fiscal year', null=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='ethiopian_submission_date',
            field=models.DateField(blank=True, help_text='Submission date in Ethiopian calendar', null=True),
        ),
    ]
