# Generated by Django 4.2.7 on 2026-05-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('filing_submitted', 'Filing Submitted'), ('filing_deadline', 'Filing Deadline'), ('payment_confirmation', 'Payment Confirmation'), ('filing_approved', 'Filing Approved'), ('filing_rejected', 'Filing Rejected'), ('penalty_notice', 'Penalty Notice'), ('general', 'General'), ('system', 'System'), ('fraud_alert', 'Fraud Alert')], max_length=30),
        ),
    ]
